### PR TITLE
Remove images deletion step from e2e test / Update test-infra

### PR DESCRIPTION
**Pull request by chaodaiG**
Old images cleanup is no longer part of e2e test, this functionality will be moved to a separate job runs periodically.

## Proposed Changes
  *This part is done in knative/test-infra, updating dependencies in this repo to include this update.

Link to the issue in test-infra: knative/test-infra#276

### CODE REVIEW

**Comment by adrcunha** [comment]
This PR unnecessarily vendored the whole test-infra repo. @chaodaiG please create a follow-up PR that updates only test-infra/scripts like https://github.com/knative/build/pull/479

**Comment by chaodaiG** [comment]
@adrcunha thanks, will do

**Pull request merged**
