### PR TITLE
Add certs secret name read from env

### PR DESCRIPTION
**Pull request by hhk7734**
# Changes

- Add certificates k8s secret name read from environment variables

/kind enhancement

- I want to change secret name when I use knative operator. 

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by hhk7734** [comment]
> Is this a dupe of #2662 ?

No. #2662 deals with the key of the `secret.data` and this deals with the `secret.metadata.name`.

**Comment by dprotaso** [comment]
We provide an option to change the secret name here:

https://github.com/knative/pkg/blob/2fdd6bf8be3190ce23acc7e8a8cb790182f635c1/webhook/webhook.go#L46-L52

**Comment by hhk7734** [comment]
> We provide an option to change the secret name for look up here:

I wanted to be able to set secret name as an environment variable when installing knative/operator.

previously, I submiited https://github.com/knative/operator/pull/1338/files. I was advised to modify knative/pkg code.
so I submitted this PR here.

**Comment by dprotaso** [comment]
/ok-to-test

Thanks for clarifying - can we adjust the names a bit to match the properties in the `webhook.Options` type

ie. `WEBHOOK_SECRET_NAME` and `webhook.SecretNameFromEnv`

```go
ctx := webhook.WithOptions(signals.NewContext(), webhook.Options{
	ServiceName: webhook.NameFromEnv(),
	Port:        webhook.PortFromEnv(8443),
	SecretName:  webhook.SecretNameFromEnv("operator-webhook-certs"),
})
```

**Comment by hhk7734** [comment]
@dprotaso I added your suggestion to this PR.

**Pull request merged**
