### PR TITLE
Update DEVELOPMENT.md

### PR DESCRIPTION
**Pull request by xtreme-sameer-vohra**
# Changes
:broom: Remove stale ref to dep as repo uses modules.

### CODE REVIEW

**Comment by xtreme-sameer-vohra** [comment]
Saw this staleness previously https://github.com/knative-sandbox/sample-controller/pull/394
The file looks pretty much identical. Would it be valuable to have some sort of automation manage it?

**Review by markusthoemmes — APPROVED** [review]
/lgtm
/approve

**Comment by xtreme-sameer-vohra** [comment]
Thanks Markus

**Pull request merged**
