### PR TITLE
SpanTree and TestSpanTree for tracing tests

### PR DESCRIPTION
**Pull request by mgencur**
This is a copy of
https://github.com/knative/eventing/blob/main/test/conformance/helpers/tracing/traces.go
with slight changes:

* Split WithHTTPHostAndPath into WithHTTPHostAndPath and WithHTTPURL.
The first one adds http.host and http.path. The second one adds
http.url. This separation allows using one or the other regardless of
Kind (Client/Server/etc.)

* MatchHTTPSpanNoReply now passes the options to the underlying
MatchHTTPSpanWithCode in the same was as MatchHTTPSpanWithReply

* Created more generic functions WithCode and MatchSpan

The whole diff can be seen here: https://pastebin.com/35Vx6e8w

Migrating this file from knative/eventing because it will be used in eventing-kafka-broker as well [in this PR](https://github.com/knative-sandbox/eventing-kafka-broker/pull/2369). 

# Changes

:gift:

/kind enhancement

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by mgencur** [comment]
The "Verify" check failed with:
```
go install: github.com/google/ko@latest: github.com/google/ko@v0.11.2 requires
	github.com/sigstore/cosign@v1.3.2-0.20211120003522-90e2dcfe7b92 requires
	github.com/google/certificate-transparency-go@v1.1.2-0.20210728111105-5f7e9ba4be3d requires
	github.com/fullstorydev/grpcurl@v1.8.2 requires
	github.com/goreleaser/goreleaser@v0.134.0 requires
	gocloud.dev@v0.19.0 requires
	github.com/Azure/azure-pipeline-go@v0.2.1: verifying go.mod: github.com/Azure/azure-pipeline-go@v0.2.1/go.mod: Get "https://sum.golang.org/tile/8/0/165": unexpected EOF
```

**Review by pierDipi — APPROVED** [review]
/lgtm

**Comment by pierDipi** [comment]
> The "Verify" check failed with:
> 
> ```
> go install: github.com/google/ko@latest: github.com/google/ko@v0.11.2 requires
> 	github.com/sigstore/cosign@v1.3.2-0.20211120003522-90e2dcfe7b92 requires
> 	github.com/google/certificate-transparency-go@v1.1.2-0.20210728111105-5f7e9ba4be3d requires
> 	github.com/fullstorydev/grpcurl@v1.8.2 requires
> 	github.com/goreleaser/goreleaser@v0.134.0 requires
> 	gocloud.dev@v0.19.0 requires
> 	github.com/Azure/azure-pipeline-go@v0.2.1: verifying go.mod: github.com/Azure/azure-pipeline-go@v0.2.1/go.mod: Get "https://sum.golang.org/tile/8/0/165": unexpected EOF
> ```
> 
> I suppose it's not caused by this PR.

it was a flake, I reran it and it's green now.

**Comment by dprotaso** [comment]
> Migrating this file from knative/eventing because it will be used in eventing-kafka-broker as well https://github.com/knative-sandbox/eventing-kafka-broker/pull/2369.

Is there an issue consuming this package from eventing?

**Comment by mgencur** [comment]
@dprotaso The span tree uses Zipkin V2 types. Both OpenCensus and OpenTelemetry can export to Zipkin by using the Zipkin types. This span tree uses the Zipkin type directly after reading the Spans from Zipkin.
It has more capabilities such as comparing individual parts using regexp, searching for a matching substree. It might be possible to use https://github.com/google/go-cmp with some custom functions for overriding equality functions but it would require some serious rewrite of the tracing test suites that currently use the SpanTree.

Consuming this package by eventing-kafka-broker directly from eventing is currently not possible because the package uses some stuff from knative/pkg which initializes flags and the tests using `reconciler-test ` initialize the flags again so I'm getting this:
```
/tmp/go-build3025671423/b001/e2e_new.test flag redefined: cluster
panic: /tmp/go-build3025671423/b001/e2e_new.test flag redefined: cluster

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc00004c240, {0x2054288, 0xc000070040}, {0x1d41e87, 0x7}, {0x1d7f4b3, 0x2e})
	/usr/local/go/src/flag/flag.go:879 +0x2f4
flag.(*FlagSet).StringVar(...)
	/usr/local/go/src/flag/flag.go:762
knative.dev/pkg/environment.(*ClientConfig).InitFlags(0xc000070040, 0xc00008e800)
	/home/mgencur/go/src/knative.dev/eventing-kafka-broker/vendor/knative.dev/pkg/environment/client_config.go:40 +0x72
knative.dev/pkg/injection.ParseAndGetRESTConfigOrDie()
	/home/mgencur/go/src/knative.dev/eventing-kafka-broker/vendor/knative.dev/pkg/injection/config.go:32 +0x36
knative.dev/pkg/injection.EnableInjectionOrDie({0x0, 0x0}, 0x0)
	/home/mgencur/go/src/knative.dev/eventing-kafka-broker/vendor/knative.dev/pkg/injection/injection.go:46 +0x94
knative.dev/eventing-kafka-broker/test/e2e_new.TestMain(0x10100b0be82b108)
	/home/mgencur/go/src/knative.dev/eventing-kafka-broker/test/e2e_new/main_test.go:64 +0x70
main.main()
```
However, it should be possible to split the package in Eventing and then in eventing-kafka-broker consume only the necessary part which doesn't initialize the flags. I'll go that way.

**Comment by mgencur** [comment]
I've sent https://github.com/knative/eventing/pull/6446 which should replace this PR.

**Comment by mgencur** [comment]
Closing this in favor of https://github.com/knative/eventing/pull/6446

**Pull request closed without merging**
