### PR TITLE
Eventing Stackdriver integration

### PR DESCRIPTION
**Pull request by nachocano**
Helps with https://github.com/knative/eventing/issues/1693

- Adding eventing metrics for integrating with Stackdriver.
- Currently, the Stackdriver exporter is tightly coupled with serving metrics. In order to iterate fast, we add here the eventing metrics as well.
- A future refactor needs to take place to move specific serving and eventing pieces out of pkg. Issue [#608](https://github.com/knative/pkg/issues/608) was filed to track those changes. It is a bigger change as it will probably involve changing the signature in UpdateExporterFromConfigMap, which is widely used throughout the code.
- Minor changes for splitting serving and eventing pieces were done in this PR, which will make the future one easier. Note files `*_eventing` or `*_serving`, which can be moved as is (and renamed).

### CODE REVIEW

**Comment by nachocano** [comment]
@yanweiguo let me know if you agree with the comments above, thanks!

**Comment by yanweiguo** [comment]
/lgtm
Please verify that it won't break metrics reporting to Stackdriver in serving.

**Comment by nachocano** [comment]
> /lgtm
> Please verify that it won't break metrics reporting to Stackdriver in serving.

Will do, do you know if there are e2e for metrics in serving?

**Comment by nachocano** [comment]
seems to be a problem with the cluster creation... 

/test pull-knative-pkg-unit-tests

**Comment by yanweiguo** [comment]
> > /lgtm
> > Please verify that it won't break metrics reporting to Stackdriver in serving.
> 
> Will do, do you know if there are e2e for metrics in serving?

I don't think so.

**Pull request merged**
