### PR TITLE
Binding duck to v1

### PR DESCRIPTION
**Pull request by nachocano**
- Creating the v1 Binding duck (equal to v1beta1)

### CODE REVIEW

**Review by n3wscott — COMMENTED** [review]
/lgtm
/approve

**Comment by nachocano** [comment]
@capri-xiyue let's sync offline. If you have cycles after you are done with the other work, it'd be great if you can investigate why the UTs are failing. We need this to promote sinkBinding to v1. I'd rather make it depend in the v1.Binding duck than the v1beta1 one. But let's sync offline

**Comment by capri-xiyue** [comment]
Test / Unit Tests (1.15.x, ubuntu-latest) (pull_request)

**Comment by nachocano** [comment]
Closing in favor of https://github.com/knative/pkg/pull/1774

**Pull request closed without merging**
