### PR TITLE
Remove all occurrences of github.com/pkg/errors.

### PR DESCRIPTION
**Pull request by markusthoemmes**
Title has it all. We don't really need this anymore since go1.13.

### CODE REVIEW

**Comment by adrcunha** [comment]
AFAIU knative/pkg is not on go 1.13 yet.

https://github.com/knative/test-infra/blob/master/ci/prow/config_knative.yaml

**Comment by markusthoemmes** [comment]
Yeah I asked in Slack why that's the case @adrcunha. Anything blocking the move there?

**Comment by adrcunha** [comment]
I remember that test flag parsing was a problem, but there were some PRs flying around to fix that. @chaodaiG and @chizhg probably know better than me.

**Comment by chaodaiG** [comment]
> I remember that test flag parsing was a problem, but there were some PRs flying around to fix that. @chaodaiG and @chizhg probably know better than me.

The test flag parsing problem was fixed by https://github.com/knative/pkg/pull/870.

I have replied on Slack regarding the go1.13, in short all other repos need to be on go1.13 before pkg can move

**Comment by vagababov** [comment]
We are waiting for all downstream systems to migrate.
But I don't know what's left.

**Comment by chizhg** [comment]
@markusthoemmes , Prow job for pkg is now running with Go 1.13 now, can you rebase this PR?

**Comment by markusthoemmes** [comment]
@chizhg rebased!

**Comment by markusthoemmes** [comment]
/assign @mattmoor 

Your superpowers are needed here!

**Pull request merged**
