### PR TITLE
Modify GKE fake client to make the operations thread-safe

### PR DESCRIPTION
**Pull request by chizhg**
Since some unit tests use go routines, modify the fake GKE client to be thread-safe.

/cc @chaodaiG

### CODE REVIEW

**Comment by chizhg** [comment]
Let's wait my local 100 test runs finish :)
/hold

**Comment by vagababov** [comment]
/hold
for comments

**Comment by vagababov** [comment]
😆

**Comment by chizhg** [comment]
/hold cancel
I have two `mutex.Lock()` in `Delete` in my last PR..

**Pull request merged**
