### PR TITLE
ran ./update-codegen.sh

### PR DESCRIPTION
**Pull request by dprotaso**
Our `knative.dev/pkg`'s codegen script wasn't invoked 

cc @shashwathi @andrew-su

### CODE REVIEW

**Comment by dprotaso** [comment]
I dunno why `test-infra` didn't catch this @coryrc - since it's using the default build runner

**Comment by andrew-su** [comment]
/lgtm

Thanks for catching that. It usually complains when update-codegen.sh isn't ran as part of `pull-knative-pkg-build-tests`.

**Comment by andrew-su** [comment]
For context, https://github.com/knative/pkg/pull/1240 was the change that update-codegen.sh should have been invoked for

**Comment by ian-mi** [comment]
Verify codegen was run on that PR, I believe the issue is #1294. codegen seems to be inconsistent since the switch to go modules.

**Comment by mattmoor** [comment]
I think I covered this in my fix in https://github.com/knative/pkg/pull/1296?

**Comment by dprotaso** [comment]
yup looks like it

**Pull request closed without merging**
