### PR TITLE
Remove re-definition of kubeconfig from pkg/test

### PR DESCRIPTION
**Pull request by n3wscott**

### CODE REVIEW

**Review by vagababov — COMMENTED** [review]
/cc @coryrc 
if we can do something better here
but in general
/lgtm

**Comment by coryrc** [comment]
`... Define your own interface.`

why?

**Comment by n3wscott** [comment]
Drat, missed one in the null class

**Comment by n3wscott** [comment]
> `... Define your own interface.`
> 
> why?

There is no need to define a central interface for the testing class, and doing so causes a circular dependency.

**Review by vagababov — COMMENTED** [review]
/lgtm

Client side interface are standard in go (in fact they are recommended pattern)

**Pull request merged**
