### PR TITLE
🧹  Bump knative.pkg deps to `v0.26.1`

### PR DESCRIPTION
**Pull request by jonathan-innis**
# Changes

- Bump knative.pkg deps to 1.26
Ran `./hack/update-k8s-deps.sh v0.26.1` which code-gened everything

/kind cleanup

Fixes #

**Release Note**

```release-note
None
```

**Docs**

```docs

```

### CODE REVIEW

**Comment by dprotaso** [comment]
/hold

We're still targeting [K8s 1.24 for our next release](https://github.com/knative/community/blob/main/mechanics/RELEASE-SCHEDULE.md#upcoming-releases) so we'll want to keep our client libs at 0.25.x - because of the K8s skew policy - ie. https://kubernetes.io/releases/version-skew-policy/#kubectl

**Comment by jonathan-innis** [comment]
@dprotaso Got it, I guess we will have to wait until then...I wonder why this one was allowed to go last time #2586. I guess the release had already started supporting 1.24 for that one

**Comment by dprotaso** [comment]
> I wonder why this one was allowed to go last time https://github.com/knative/pkg/pull/2586

Yeah - Knative 1.8 targeted K8s 1.23 which is supported by client-go 1.24 libs.  We pull in client-go libs N+1 when we target K8s version N.

**Comment by dprotaso** [comment]
I'm gonna close this out as we'll revisit this at a later date

**Pull request closed without merging**
