### PR TITLE
Fixes #2308 TestSpoofingClient_WaitForEndpointState flake

### LINKED ISSUE #2308: Flakey test TestSpoofingClient_WaitForEndpointState/Non_matching_response_triggers_more_requests
TestSpoofingClient_WaitForEndpointState/Non_matching_response_triggers_more_requests 

Details: https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_pkg/2302/pull-knative-pkg-unit-tests/1445830894286802944

### PR DESCRIPTION
**Pull request by dprotaso**
Fixes: #2308

### CODE REVIEW

**Comment by dprotaso** [comment]
whoops - didn't refresh the page

**Review by pierDipi — APPROVED** [review]
/lgtm

**Pull request merged**
