### PR TITLE
Add a parallel test to upgrade test framework to assert no race conditions are present

### PR DESCRIPTION
**Pull request by cardil**
This is just to showcase that parallel steps in new upgrade test framework do work.

### CODE REVIEW

**Comment by cardil** [comment]
Of course, it produces a race... I didn't bother to write it with channels, as this is just to showcase that operations in single steps can by running in parallel. That should be enough, as other types of parallelism seams unwanted.

/cc @mgencur

**Comment by markusthoemmes** [comment]
Still required?

**Comment by cardil** [comment]
Yeah. Maybe, I'll add this test to the framework, so the support would be explicit, and fixing the race in the same time.

/remove-lifecycle stale

**Comment by markusthoemmes** [comment]
What's the goal of this PR? Is this supposed to land at some point? What's missing?

**Pull request closed without merging**
