### PR TITLE
Use *url.URL instead of string in request.go

### PR DESCRIPTION
**Pull request by JRBANCEL**
Fixes https://github.com/knative/serving/issues/5419 - Part I

See corresponding `knative.dev/serving` change: https://github.com/knative/serving/pull/5503

/hold

### CODE REVIEW

**Comment by mattmoor** [comment]
/approve
/hold

This change is breaking, and so we should wait until after the downstream repos are picking up changes again before landing it, and stage changes to import this into repos that it breaks.

**Comment by JRBANCEL** [comment]
@mattmoor, the corresponding `knative.dev/serving` is https://github.com/knative/serving/pull/5503.
These methods are not used in `knative.dev/eventing`.

Do you I something do something else?

**Comment by mattmoor** [comment]
@JRBANCEL no, that's the usual routine, but serving is parked on the knative/pkg `release-0.9` branch until tomorrow morning.  I left a couple comments on the serving PR, but once that's ready then this is good to go, I just want to minimize the amount of downtime due to breaking changes here.

**Comment by JRBANCEL** [comment]
https://github.com/knative/serving/pull/5503 tests are passing.
/hold cancel

**Pull request merged**
