### PR TITLE
Add perf test cluster manager

### PR DESCRIPTION
**Pull request by chizhg**
Add a library to manager clusters for performance tests, as what has been reviewed in https://github.com/knative/test-infra/pull/1459.

/cc @chaodaiG

### CODE REVIEW

**Comment by chaodaiG** [comment]
Since this has been fully reviewed in knative/test-infra#1459, skip reviewing this one
/lgtm
/approve

/hold
In case @adrcunha or @vagababov have some ideas

**Comment by adrcunha** [comment]
I'm confused. 1459 was not merged, and this PR contains files that are not in 1459.

**Comment by chizhg** [comment]
> I'm confused. 1459 was not merged, and this PR contains files that are not in 1459.

As Chao and I previously discussed, we plan to put all the Go code under `pkg` and only keep the shell script under `test-infra`. I have closed 1459 and opened https://github.com/knative/pkg/pull/776, which needs this PR to be merged first.

**Pull request merged**
