### PR TITLE
drop kubeclient struct

### PR DESCRIPTION
**Pull request by dprotaso**
- [x] https://github.com/knative-sandbox/net-istio/pull/664
- [x] https://github.com/knative/operator/pull/655
- [x] https://github.com/knative/eventing/pull/5491

### CODE REVIEW

**Comment by dprotaso** [comment]
/hold

will remove some stuff downstream

**Comment by dprotaso** [comment]
Just waiting for downstream PRs to merge

**Comment by dprotaso** [comment]
unholding - the remaining repos will be resolved once they picked up the eventing change

**Review by markusthoemmes — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
