### PR TITLE
Function AllowRestrictedPodSecurityStandard for modifying test pods

### PR DESCRIPTION
**Pull request by mgencur**
Related to https://github.com/knative/eventing/issues/6563
The changes from this PR are used in the implementation of the above issue: https://github.com/knative/eventing/pull/6584
Sending this to knative.dev/pkg because the function will be used in Knative Eventing, Eventing Kafka, Eventing Kafka Broker, reconciler-test. 

# Changes
- Allow adding SecurityContext to test Pods depending on its labels which allows them to run in Kubernetes with "restricted" pod security admission and is backwards compatible with Kubernetes 1.21

- :gift:

/kind enhancement

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by mgencur** [comment]
/assign @dprotaso 
Please review. Thanks in advance

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by dprotaso** [comment]
Just curious why `reconciler-test` would need this helper?

Otherwise this seems more specific to eventing and might be a better place for it there

**Comment by mgencur** [comment]
@dprotaso Here's the example usage in reconciler-test: https://github.com/knative-sandbox/reconciler-test/pull/414/files#diff-49062e7fa4a39e10ec46179cc35648044120971a7cabb271ab538fac480c99e7R33
It uses both the function IsRestrictedPodSecurityEnforced and the default values for PodSecurityContext and ContainerSecurityContext.

**Comment by mgencur** [comment]
Thanks!

**Pull request merged**
