### PR TITLE
Derive the config for our controller setup like kubectl etc.

### PR DESCRIPTION
**Pull request by markusthoemmes**
Our config loading currently only tries the given flags or in-cluster config. This also adds the KUBECONFIG env variable and the user's home directoy as fallback solutions to find a valid configuration.

That helps running our controllers locally with minimal effort.

### CODE REVIEW

**Comment by dprotaso** [comment]
Seems like client-go defaults must be broken

 from `clientcmd.BuildConfigFromFlags` [godoc](https://godoc.org/k8s.io/client-go/tools/clientcmd#BuildConfigFromFlags)
> If neither masterUrl or kubeconfigPath are passed in we fallback to inClusterConfig. If inClusterConfig fails, we fallback to the default config.

**Comment by markusthoemmes** [comment]
@dprotaso Nope, that sentence remains true. "default config" just isn't what we're after. This command does not look at the environment variable neither does it fall back to the user's home location. The default config is simply an empty config I think?

**Comment by dprotaso** [comment]
that sucks - what you want is there though
https://github.com/kubernetes/client-go/blob/master/tools/clientcmd/loader.go#L141

I guess it's not wired into `BuildConfigFromFlags`

**Pull request merged**
