### PR TITLE
Add kmp, a safe wrapper for google/go-cmp

### PR DESCRIPTION
**Pull request by jonjohnsonjr**
* Returns an error instead of panicking.
* Holds common options that we use.

See: https://github.com/knative/serving/issues/2622

### CODE REVIEW

**Comment by jonjohnsonjr** [comment]
@mattmoor this is what I had in mind. I think we'll eventually want to get rid of any non-test usage of cmp, but we can use this in the meantime.

**Comment by jonjohnsonjr** [comment]
Great naming suggestions from @tcnghia:
* `kmp` instead of `cmp`
* `SafeDiff` instead of `Diff`

Happy to 🚲 🏠 but I like those 😄

**Comment by vaikas-google** [comment]
would it be useful to try to get these upstreamed?

**Comment by jonjohnsonjr** [comment]
I suspect they would be amenable to a non-panicky variant of `Diff`.

I just found [this comment](https://github.com/google/go-cmp/pull/97#issuecomment-438820774) that proposes a new option: `cmpopts.AllowUnexported(cmpopts.PackagePath("k8s.io"))`. If both of those would land, we could ditch this package.

@dsnet any thoughts on returning an error instead of panicking? Also 👍 to a `PackagePath` option.

**Pull request merged**
