### PR TITLE
[WIP] Allow specifying operations of a webhook rule for a resource

### PR DESCRIPTION
**Pull request by pierDipi**
Allow specifying operations of a webhook rule for a resource.

# Changes

- Allow specifying operations of a webhook rule using `OperationTypes` extension interface

/kind enhancement

### CODE REVIEW

**Comment by pierDipi** [comment]
Hi @markusthoemmes, @julz, @dprotaso can you please review this PR?

**Comment by julz** [comment]
can you say a bit more about the context / use case etc? (or a link to an issue if there is one maybe)

**Comment by pierDipi** [comment]
I don't have a specific issue, basically, I need to update a resource (`setDefaults`) only when it is created and it's unnecessary call the webhook on updates.

**Comment by dprotaso** [comment]
> I don't have a specific issue, basically, I need to update a resource (setDefaults) only when it is created and it's unnecessary to call the webhook on updates.

This is problematic and assumes only one actor in the system. In theory you could have some other component in the system modifying your object on `UPDATE`. So I would recommend validating the object.

**Comment by pierDipi** [comment]
The field that I want to change is immutable.

**Comment by dprotaso** [comment]
> Yes, the field that I want to change is immutable.

Can you share more context about what's happening and why?

**Comment by pierDipi** [comment]
I need to change the `Volumes` field of a `Pod` (and related `VolumeMounts`) because I need to mount a different `ConfigMap` for each `Pod` created by a `Deployment`.

**Comment by dprotaso** [comment]
What's immutable in that scenario?

**Comment by pierDipi** [comment]
`Volumes` cannot be changes on raw pods

**Comment by pierDipi** [comment]
https://kubernetes.io/docs/concepts/workloads/pods/#pod-update-and-replacement

> Pod updates may not change fields other than spec.containers[\*].image, spec.initContainers[\*].image, spec.activeDeadlineSeconds or spec.tolerations. For spec.tolerations, you can only add new entries.

**Comment by pierDipi** [comment]
Closing this, for now, @dprotaso suggested solving this by using callbacks.

**Pull request closed without merging**
