### PR TITLE
remove source stats reporter it's been moved to knative.dev/eventing/pkg/metrics/source

### PR DESCRIPTION
**Pull request by dprotaso**
Fixes: https://github.com/knative/pkg/issues/608

### CODE REVIEW

**Comment by skonto** [comment]
I guess we need to create downstream PRs as well?

**Comment by dprotaso** [comment]
Yup that's already done:

Transition PR using type aliases: 
https://github.com/knative/eventing/pull/5587

Adopt new package: 
knative-sandbox/eventing-rabbitmq#362
knative-sandbox/eventing-kafka#765

Move the code over
https://github.com/knative/eventing/pull/5594

**Comment by vaikas** [comment]
Even though: knative-sandbox/eventing-rabbitmq#362 is in, the downstream for it is failing?
Also looks like bunch of other tests are failing also.

**Comment by dprotaso** [comment]
I think those downstream deps don't have the latest eventing deps - let me check

**Comment by dprotaso** [comment]
/hold
ie. Yeah this needs to merge: https://github.com/knative-sandbox/eventing-rabbitmq/pull/363

I'll do the rounds and approve those update deps PRs

**Comment by dprotaso** [comment]
/hold cancel

ok all downstream repos have the latest eventing dep update which causes everything here to go green

**Comment by vaikas** [comment]
Thanks @dprotaso 
/lgtm
/approve

**Pull request merged**
