### PR TITLE
drop the default log url template

### PR DESCRIPTION
**Pull request by dprotaso**
this had references to the monitoring bundle which is being removed here: https://github.com/knative/serving/pull/9807

### CODE REVIEW

**Comment by dprotaso** [comment]
interesting logstream flaked 

```go
--- FAIL: TestNamespaceStream (1.00s)
    stream_test.go:87: timed out: log message wasn't received
```

**Comment by vagababov** [comment]
This will break stuff.
We use it in the serving.

**Comment by dprotaso** [comment]
https://github.com/knative/serving/pull/9807

**Comment by vagababov** [comment]
I think the default _is not_ an empty string anymore. Those were the changes we did recently.
Since we added a new boolean toggle so default _always_ has a value now.

**Comment by dprotaso** [comment]
> I think the default _is not_ an empty string anymore. Those were the changes we did recently.
> Since we added a new boolean toggle so default _always_ has a value now.

I'm confused - the logging template is a string value

**Comment by vagababov** [comment]
Yes it always has a value now.

Initial implementation was:
```
if template == "" { no logging }
else {use the template}
```

And the default value was empty.

Current is
```
if !enable_logging {no logging}
else {use the template}
```

And template is *always* non empty now (since the toggle is false by default).
Test here: https://github.com/knative/serving/blob/master/pkg/metrics/config_test.go verify that.
Also it has to match the example set in config/core/configmaps/observability.yaml.

**Comment by dprotaso** [comment]
it looks like the change your made was for the request log template

I'm changing the `DefaultLogURLTemplate`

**Comment by vagababov** [comment]
Too many templates! :-)

I think it still has to be non-empty so that we can have a non-empty example.

**Comment by dprotaso** [comment]
> I think it still has to be non-empty so that we can have a non-empty example.

I'm going to drop that bit of logic in serving

**Comment by vagababov** [comment]
Which part? Checking in UT that the example value is not empty?

**Comment by vagababov** [comment]
Not really. We actually had an issue about that. 
Why do you want to drop the default?

**Comment by dprotaso** [comment]
> Why do you want to drop the default?

With the monitoring bundle gone an empty default make sense - but we _would_ want an example that highlights the revision UID substitution

**Comment by dprotaso** [comment]
downstream serving fix is here: https://github.com/knative/serving/pull/9807

**Comment by vagababov** [comment]
The problem with example not matching the default, is that just copy-pasting example as actual config is going to break stuff. Which might or might not be expected :)

Anyway, I am not going to fight this a lot :)

/cc @mattmoor 
For more insights :)

**Review by mattmoor — COMMENTED** [review]
/lgtm

**Pull request merged**
