### PR TITLE
Backport Eventing StackDriver metrics to release-0.10 (#846)

### PR DESCRIPTION
**Pull request by nachocano**
* Updating StackDriver metrics for eventing.
* Original PR in master https://github.com/knative/pkg/pull/846

### CODE REVIEW

**Comment by nachocano** [comment]
Some cluster creation problem: 
`2019/11/07 18:11:12 Error during cluster creation: 'timed out waiting'. Retry another region "us-west1" for cluster creation`

rerunning UTs

**Comment by evankanderson** [comment]
Discussed this with @nachocano 

I'm going to:

/lgtm
/approve

For now, but all this Stackdriver/Google-specific metrics stuff living in `pkg` is not what was intended, and we should aim for 0.11 to have a properly pluggable metrics subsystem so that "knative.dev/internal/..." stuff for Google integration can be done in a Google-specific repo rather than at the font of all waters.

**Pull request merged**
