### PR TITLE
Scott to owners on pkg

### PR DESCRIPTION
**Pull request by n3wscott**

### CODE REVIEW

**Review by mattmoor — COMMENTED** [review]
/lgtm
/approve

**Comment by mattmoor** [comment]
@grantr yeah I got sick of approving changes to code he largely wrote 😉

**Comment by n3wscott** [comment]
/retest

I am gonna kill that flake tomorrow.

**Comment by n3wscott** [comment]
Cool, codecov is blocking the pr

**Review by mattmoor — COMMENTED** [review]
/lgtm

**Pull request merged**
