### PR TITLE
Bump K8s libs to 1.19

### LINKED ISSUE #1881: Bump k8s libs to 1.19
/area API
/area test-and-release
/kind feature

This is similar request to https://github.com/knative/pkg/issues/1280, but for v1.19.

For example, service-apis repo uses [client-go v0.19.2](https://github.com/kubernetes-sigs/service-apis/blob/3fdc5d3fb0a864d186c709f6b22d6bba088d1688/go.mod#L12) and so we hit a dependency error when using the latest service-apis in knative/networking repo.

/cc @dprotaso @mattmoor

### PR DESCRIPTION
**Pull request by dprotaso**
Fixes #1881

**Release Note**

```release-note
NONE
```

~/hold - confirming we can use 1.18 in GKE (https://knative.slack.com/archives/CCSNR4FCH/p1610581340198700)~

We're good - using the regular channel in us-east1 has 1.18 clusters

### CODE REVIEW

**Comment by dprotaso** [comment]
unf - need to fix the case name on the folder

**Comment by dprotaso** [comment]
We now use us-east1 which has 1.18 in the regular release channel so we should be good to merge

**Comment by vagababov** [comment]
/lgtm
/approve

🎉

**Pull request merged**
