### PR TITLE
switch to klog/v2

### PR DESCRIPTION
**Pull request by dprotaso**
client-go and k8s now uses klog/v2 we should drop our use of klog v1

### CODE REVIEW

**Comment by dprotaso** [comment]
unit test flake
```
TestSpoofingClient_WaitForEndpointState/Non_matching_response_triggers_more_requests 
```

**Comment by dprotaso** [comment]
operator issue is resolved by https://github.com/manifestival/manifestival/pull/87

**Comment by nader-ziada** [comment]
the failing test in `Downstream Knative/Unit Test` is a flakey test I have seen fail in other PRs and then pass on a re-run

**Pull request merged**
