### PR TITLE
Updates to the release process with 0.20

### PR DESCRIPTION
**Pull request by slinkydeveloper**
This includes a list of updates to the release process from @nak3 and I during the 0.20 release

Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

# Changes

- Reorganized and enhanced the paragraph explaining the actual repository release
- Added additional explanation of the state of `go.mod` file before the cut
- We don't need to cut net-kourier after serving as it does not depend on Serving repo.
- Added `reconciler-test` cut

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
@nak3 can you try again to fix the cla bot?

**Comment by nak3** [comment]
@googlebot I consent.

**Review by n3wscott — COMMENTED** [review]
/lgtm

**Comment by n3wscott** [comment]
Would love someone else to review too, like @mattmoor

**Comment by mattmoor** [comment]
/assign @lionelvillard 

Tagging Lionel, since he's my co-release lead this cycle

**Comment by slinkydeveloper** [comment]
@mattmoor I rebased

**Review by mattmoor — APPROVED** [review]
/lgtm

**Pull request merged**
