### PR TITLE
Add dependabot configuration

### PR DESCRIPTION
**Pull request by pierDipi**
# Changes

- Add dependabot configuration

### CODE REVIEW

**Comment by markusthoemmes** [comment]
Thanks for trying this out! We'll have to make sure this doesn't butcher our K8s deps though. Your experiments showed that it currently does (see https://github.com/pierDipi/pkg/pull/4). Can we ignore k8s dep bumps?

**Comment by pierDipi** [comment]
https://github.com/pierDipi/pkg/pull/4#issuecomment-739856702

**Review by markusthoemmes — APPROVED** [review]
I like, don't see a reason not to try this out!

I'll hold off on a LGTM to get input from more peeps. Thanks for playing with this!

**Comment by pierDipi** [comment]
Probably this https://github.com/pierDipi/pkg/blob/db193b096f34d415da6e3e3fefb6ac231ee0bc4b/hack/update-deps.sh#L52-L53, won't work on verify because it includes OWNERS files: https://github.com/pierDipi/pkg/pull/5/files#diff-70721b9094f3050454588463842e68eef3e12218fa7bd22455c5948052ad4614R1.

**Comment by pierDipi** [comment]
Does having OWNERS in a vendor dir break Prow?

**Comment by markusthoemmes** [comment]
Oh yeah, yes it does :(. We'll have to run a script after updating go.mod.

**Comment by markusthoemmes** [comment]
/hold

/assign @mattmoor @n3wscott 

See above, we currently can't have nice things like dependabot because of our additional massaging of `go mod vendor`. I wonder if we should consider leaving it alone instead :thinking:.

**Comment by mattmoor** [comment]
There are enough gotchas that I'm reluctant to enable it wholesale.  Top of mind:
1. License compliance
2. Carrying patches
3. Removing symlinks

Most of the rest I've seen feel cosmetic.  Could we instead run it as an action with some of our extra cleanup logic as a post-step?

**Comment by pierDipi** [comment]
@mattmoor we can run an action on a PR created by Dependabot and commit the diff.
In that case, the PR would have 1 commit from Dependabot and 1 commit from Knobots.
Unclear how that plays with the CLA bot.

**Pull request closed without merging**
