### PR TITLE
Downstream is updated, to remove outdated methods

### PR DESCRIPTION
**Pull request by vagababov**
/assign mattmoor @tcnghia

### CODE REVIEW

**Review by tcnghia — APPROVED** [review]
/lgtm

**Comment by mattmoor** [comment]
/hold

Can you confirm Tekton isn't using these?

**Comment by vagababov** [comment]
Nobody uses those except eventing
since they are used for some dynamic reconfig

**Comment by vagababov** [comment]
(But I checked, they are only pulled in as dependencies with no usage)

**Pull request merged**
