### PR TITLE
Remove pkg/pool

### PR DESCRIPTION
**Pull request by imjasonh**
Fixes https://github.com/knative/pkg/issues/2556

# Changes

🗑️ Remove pkg/pool

/kind cleanup

**Release Note**

```release-note
pkg/pool is removed, use errgroup instead
```

**Docs**

```docs
NONE
```

cc @dprotaso

### CODE REVIEW

**Comment by dprotaso** [comment]
/lgtm
/approve
/override Downstream Tekton / Unit Test (tektoncd/chains) (pull_request) 
/override Downstream Tekton / Unit Test (tektoncd/pipeline) (pull_request)

**Comment by dprotaso** [comment]
override Tekton - since I assume you'll fix those :)

**Comment by imjasonh** [comment]
Chains fix: https://github.com/tektoncd/chains/pull/517 -- bumps cosign and knative/pkg deps
Pipeline fix: https://github.com/tektoncd/pipeline/pull/5311 -- bumps knative/pkg dep, accounts for new `changeset.Get` behavior

**Pull request merged**
