### PR TITLE
update k8s to 1.25.2

### LINKED ISSUE #2598: Kubernetes v1.25 deprecation tracking
Opening this as an umbrella to track the various deprecations in k8s v1.25: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25

* CronJob
* EndpointSlice
* Event
* HorizontalPodAutoscaler
* PodDisruptionBudget
* PodSecurityPolicy
* RuntimeClass

Note that not all of these may impact us / still need to fill in the details / etc.

### PR DESCRIPTION
**Pull request by nader-ziada**
# Changes
- update k8s library to 1.25.2

Fixes #2598 

**Release Note**

```release-note
Update k8s library to 1.25.2
```
/cc @psschwei

### CODE REVIEW

**Comment by nader-ziada** [comment]
@pierDipi @lionelvillard seems all the eventing downstream tests get broken with the update to k8s 1.25.2, I think a big part of it is updating the version of cloud-events

**Comment by lionelvillard** [comment]
retesting after https://github.com/knative/eventing/pull/6552

/retest

**Comment by lionelvillard** [comment]
It's an antlr problem. k8s 1.25 picks up a newer not-backward compatible antlr. I'll submit a PR in the ce SDK repo.

**Comment by lionelvillard** [comment]
btw k8s 1.25 requires go 1.19. It does not seem to use any new go features so the build does not break but I think it's probably better to align with what k8s is doing.

**Comment by lionelvillard** [comment]
/retest

For eventing.

**Comment by nader-ziada** [comment]
> /retest
> 
> For eventing.

seems like a different issue this time

**Comment by nader-ziada** [comment]
@lionelvillard 

do you think we can get this fixed for the release next week?

**Comment by nader-ziada** [comment]
@lionelvillard @psschwei does this PR need to be merged in first then we fix the downstream issues? or how does this work?

**Comment by psschwei** [comment]
> @lionelvillard @psschwei does this PR need to be merged in first then we fix the downstream issues? or how does this work?

Yeah, we should make the update here first and then the fixes downstream, assuming everyone's ready. We should be good from the serving side, @lionelvillard can confirm for eventing.

**Comment by lionelvillard** [comment]
the only caveat is easycla is broken for knative/eventing

**Comment by psschwei** [comment]
EasyCLA should be fixed now, so...

**Review by psschwei — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
