### PR TITLE
Allow skipping conversion crd update

### PR DESCRIPTION
**Pull request by skonto**
# Changes

- Downstream we need skip the crd update as this is done by OLM. See https://github.com/openshift-knative/serverless-operator/pull/2597
- We would like to be able to delegate crd updates and only keep the reconciler for validation.

/kind enhancement

### CODE REVIEW

**Comment by dprotaso** [comment]
Why not just delete the conversion webhook controller from your binary?

**Comment by skonto** [comment]
> Why not just delete the conversion webhook controller from your binary?

We keep this aligned with the knative/operator https://github.com/knative/operator/blob/main/config/crd/bases/operator.knative.dev_knativeservings.yaml#L2470
Not sure what is coming next (if any major change) like from v1beta1 to v1 for example. :shrug:

**Comment by skonto** [comment]
@dprotaso wdyth about my last comment?

**Comment by dprotaso** [comment]
I guess I'm still confused are you looking to skip conversion or skip the reconciliation that updates the cacert and service path?

If it's the CA cert then don't we have the knobs(options) to change the default secret and properties?


> We keep this aligned with the knative/operator https://github.com/knative/operator/blob/main/config/crd/bases/operator.knative.dev_knativeservings.yaml#L2470

I don't think you need to set that - it will default to what the API server supports - which is probably `v1` now? v1beta1 and v1 are equivalent (or it was when I last looked)

**Comment by dprotaso** [comment]
I'm going to close this out - i think downstream it just makes sense to drop the certificate reconciler from the webhook controller

**Comment by skonto** [comment]
> I guess I'm still confused are you looking to skip conversion webhook callbacks or skip the reconciliation that updates the cacert and service path?

I wanted to skip the update of the cacert as this is done from another operator.

> v1beta1 and v1 are equivalent (or it was when I last looked)
> I'm going to close this out - i think downstream it just makes sense to drop the certificate reconciler from the webhook controller

I wanted to keep this around in case there is a migration to v1, probably not?

**Pull request closed without merging**
