### PR TITLE
use k8s.interface

### PR DESCRIPTION
**Pull request by n3wscott**
Use  `kubernetes.Interface` over `*kubernetes.Clientset` and `*test.Client`.

The change to the helpers is a breaking change, but simple to fix downstream.

### CODE REVIEW

**Comment by n3wscott** [comment]
/hold
I want to do something from the last review.

**Comment by mattmoor** [comment]
/lgtm
/hold

HOLD so you can stage as needed, then `/unhold`.  Thanks for splitting this out.

**Comment by n3wscott** [comment]
Serving ready: https://github.com/knative/serving/pull/9818

**Comment by n3wscott** [comment]
Eventing Ready: https://github.com/knative/eventing/pull/4321

There are a few more downstreams that will break, but they dep on serving and eventing to be updated. I can get to them today as I find them.

**Comment by n3wscott** [comment]
/unhold

Serving and Eventing are ready, they have additional downstreams that will break, we will take them in tern in the next 8 hours. GO

**Pull request merged**
