### PR TITLE
support multiple cleanup functions

### PR DESCRIPTION
**Pull request by dprotaso**
note: this change is backwards compatbile

### CODE REVIEW

**Comment by vagababov** [comment]
Probably needs a comment about the order of execution?

**Comment by dprotaso** [comment]
Curious if the timing of 100 milliseconds isn't good enough

**Comment by dprotaso** [comment]
well that test became ugly lol

**Comment by dprotaso** [comment]
hmm.. there's a lot more uses of the `CleanupOnInterrupt` than I thought. I'll do this change gracefully

**Review by psschwei — COMMENTED** [review]
@dprotaso Only comment I have is, should this be rebased to a single commit? (It didn't look like that was listed as a requirement in the docs anywhere, but thought I'd mention it just in case) Looks good to me otherwise.

**Comment by dprotaso** [comment]
@psschwei we have prow setup to do the merging and it will squash all the commits

Thus adding new commits generally makes it easier to review vs. force pushing etc.

**Comment by psschwei** [comment]
That's cool, I didn't know that
/lgtm

**Pull request merged**
