### PR TITLE
Enhance controller to pass context

### PR DESCRIPTION
**Pull request by jinchihe**
# Changes

I defined the key/value in context, but cannot pass to reconcile, the root cause is the context is not passed to `processNextWorkItem` below:
https://github.com/knative/pkg/blob/9d92ea16c0d3b2b03ac456782563321030726280/controller/controller.go#L468

The PR is going to fix the issue to pass context. Thanks.

/kind bug

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Review by markusthoemmes — COMMENTED** [review]
Could you elaborate on why you need this? I think we're not passing the "big" context to each reconcile by design currently.

**Comment by jinchihe** [comment]
@markusthoemmes Thanks. I made a new controller basic on knative framework, and I would like to pass some args from controller main to reconcile by `context` so that the `reconcile` can handle some logic basic on the args, but I found the org context is not passed, and create new context in `processNextWorkItem`. Personally I think the context should be coherent, and not sure how big the context for general cases.

by the way, here shows the  `controller/controller.go` is conflicting, that's weird, I fetch and rebase, nothing new, what's problem here? Thanks.
```
➜  pkg git:(enhance_controller_to_pass_ctx) git fetch upstream
➜  pkg git:(enhance_controller_to_pass_ctx) git rebase upstream/master
Current branch enhance_controller_to_pass_ctx is up to date.
➜  pkg git:(enhance_controller_to_pass_ctx) git push origin enhance_controller_to_pass_ctx -f
Everything up-to-date
➜  pkg git:(enhance_controller_to_pass_ctx)
```

**Comment by markusthoemmes** [comment]
The current way of sharing information from `NewController` into `Reconcile` is by adding them to the reconciler type. Is that not possible here?

**Comment by jinchihe** [comment]
@markusthoemmes Thank you. yeah, in fact I can get this by others such as define a ENV or read from config map etc.. my point is if we need ensure the context to be coherent. Thanks.

**Comment by markusthoemmes** [comment]
At least currently, I think the context's not inheriting from each other is by-design. Summoning @n3wscott for input.

**Comment by jinchihe** [comment]
OK So I will close the PR, thanks @markusthoemmes

**Pull request closed without merging**
