### PR TITLE
Make example types KRShaped

### PR DESCRIPTION
**Pull request by whaught**
- Ensure the test example resources are KRShaped.

### CODE REVIEW

**Comment by antoineco** [comment]
@whaught 

```
# knative.dev/pkg/apis/test/example/v1alpha1
apis/test/example/v1alpha1/fiz_types.go:52:5: cannot use (*ClusterFiz)(nil) (type *ClusterFiz) as type kmeta.OwnerRefable in assignment:
	*ClusterFiz does not implement kmeta.OwnerRefable (wrong type for GetObjectMeta method)
		have GetObjectMeta() *"k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta
		want GetObjectMeta() "k8s.io/apimachinery/pkg/apis/meta/v1".Object

apis/test/example/v1alpha1/foo_types.go:51:5: cannot use (*Foo)(nil) (type *Foo) as type kmeta.OwnerRefable in assignment:
	*Foo does not implement kmeta.OwnerRefable (wrong type for GetObjectMeta method)
		have GetObjectMeta() *"k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta
		want GetObjectMeta() "k8s.io/apimachinery/pkg/apis/meta/v1".Object
```
```
# knative.dev/pkg/apis/test/pub/v1alpha1
apis/test/pub/v1alpha1/bar_types.go:51:5: cannot use (*Bar)(nil) (type *Bar) as type kmeta.OwnerRefable in assignment:
	*Bar does not implement kmeta.OwnerRefable (wrong type for GetObjectMeta method)
		have GetObjectMeta() *"k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta
		want GetObjectMeta() "k8s.io/apimachinery/pkg/apis/meta/v1".Object
?   	knative.dev/pkg/signals	[no test files]
```

**Comment by whaught** [comment]
@antoineco That should be resolved. There was a conflict with the existing GetObjectMeta interface (which we are now using).

**Pull request merged**
