### PR TITLE
Fixed #1057 - Rename ConvertUp/Down to ConvertTo/From

### LINKED ISSUE #1057: apis.Convertible has confusing function names
What `ConvertUp` & `ConvertDown` should do isn't immediately obvious. 

https://github.com/knative/pkg/blob/79f10450c2609c682a2dae3762adb867c504f15b/apis/interfaces.go#L37-L45

Suggested Alternative
- `ConvertTo` & `ConvertFrom`

### PR DESCRIPTION
**Pull request by dprotaso**
### Downstream PRs

- [x] knative/serving - https://github.com/knative/serving/pull/6986
- [x] knative/eventing - https://github.com/knative/eventing/pull/2632
- [x] knative/eventing-contrib - noop
- [x] knative/sample-controller - noop
- [x] knative/sample-source - noop

### CODE REVIEW

**Comment by dprotaso** [comment]
`knative/serving` - https://github.com/knative/serving/pull/6986

**Comment by n3wscott** [comment]
Might be easier to deprecate the old names and add the new one and then delete the old one?

**Comment by dprotaso** [comment]
> Might be easier to deprecate the old names and add the new one and then delete the old one?

Easier for who?

**Comment by dprotaso** [comment]
`knative/eventing` - https://github.com/knative/eventing/pull/2632

**Comment by dprotaso** [comment]
This is technically a NOOP and just a dependency bump
`knative/eventing-contrib` - https://github.com/knative/eventing-contrib/pull/961

**Comment by dprotaso** [comment]
`knative/sample-controller` - no usage

**Pull request merged**
