### PR TITLE
Remove long deprecated NewImplWithStats

### PR DESCRIPTION
**Pull request by mattmoor**
/kind cleanup

**Release Note**

```release-note
Remove deprecated controller.NewImplWithStats constructor
```

**Docs**

```docs

```

### CODE REVIEW

**Comment by mattmoor** [comment]
Let's see what the downstream tests have to say 🍿

**Review by n3wscott — APPROVED** [review]
/lgtm
/approve

**Comment by mattmoor** [comment]
/hold

This'll conflict with the other and I'll rebase it

**Comment by mattmoor** [comment]
/unhold

Maybe not 🤔

**Comment by mattmoor** [comment]
/retest
unit test flake 🙃

**Pull request merged**
