### PR TITLE
timer set to nil after draining period

### PR DESCRIPTION
**Pull request by Shashankft9**
# Changes

- :bug: sets timer to nil once the draining period wait is over

/kind bug

Fixes https://github.com/knative/serving/issues/12571

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Review by psschwei — COMMENTED** [review]
Ran this patch locally to verify it fixes the issue in https://github.com/knative/serving/issues/12571 (and concurrently verified the issue still exists in Serving v1.4.0) 

/lgtm

**Comment by geekifier** [comment]
@Shashankft9 looks like you need to `/assign @vagababov` to move this PR forward.

**Comment by Shashankft9** [comment]
I think @dprotaso also wanted to review this.
cc @skonto

**Comment by geekifier** [comment]
Guys, any chance to review this? We have been stuck on pre-1.0 Knative because of this issue.

**Comment by dprotaso** [comment]
closing in favour of https://github.com/knative/pkg/pull/2572

The implementation here means subsequent calls to `Drain` wouldn't behave the same way (after the first drain is complete).

I opt'd to add `Reset` function to the drainer

**Pull request closed without merging**
