### PR TITLE
Register the dynamic informer factory

### PR DESCRIPTION
**Pull request by lionelvillard**
See https://github.com/knative/eventing/issues/2154 for context.

### CODE REVIEW

**Comment by lionelvillard** [comment]
@Harwayne @nachocano @aslom

**Comment by vaikas** [comment]
Can we not use the existing Duck based stuff to achieve what you're trying to do? Based on the issue we should be able to use the PodSpecable with the existing duck machinery. Or, are you trying to then later on add the concrete types as just go structs without vendoring the serving tree? If so, what's the plan for actually creating the resources?

Just trying to understand the plan here.

**Comment by n3wscott** [comment]
Checkout `+genduck` https://github.com/knative/pkg/blob/43ca049cdbdad4892b0c926e7c6536d064efde72/apis/duck/v1/addressable_types.go#L30

It might be what you really want.

**Comment by lionelvillard** [comment]
Ah yes genduck. I'll look at it, thanks.

**Pull request closed without merging**
