### PR TITLE
cleanup: update a bunch of deps

### PR DESCRIPTION
**Pull request by k4leung4**
# Changes

Update various go deps to avoid dep conflicts for downstream usage

- 🧹 cleanup: update a bunch of deps

/kind cleanup

Fixes #

**Release Note**

```release-note
NONE
```

**Docs**

```docs

```

### CODE REVIEW

**Comment by nak3** [comment]
/lgm

Thank you @k4leung4 ! BTW, I'm proposing the automation of 3rd party libs https://github.com/knative/pkg/issues/2759 and please jump in the discussion if you have any opinion.

**Comment by dprotaso** [comment]
thanks @k4leung4

**Pull request merged**
