### PR TITLE
Update OnChanged in tracker to support deletion events

### PR DESCRIPTION
**Pull request by lichuqiang**
To address https://github.com/knative/serving/pull/2376#issuecomment-435089263

### CODE REVIEW

**Comment by lichuqiang** [comment]
Yeah! I can also feel the necessity to shape our own abstraction based on our scenarios.
I just did not made the determination (or got time) to manage it here in this PR.

**Comment by mattmoor** [comment]
Ok, we will also need `EnsureTypeMeta` supports deletion before we can use this effectively for deletion events.

**Comment by lichuqiang** [comment]
I've updated to expose the interface, PTAL

**Comment by lichuqiang** [comment]
Time to remove the `hold` ?

**Comment by mattmoor** [comment]
/hold cancel

Thanks @lichuqiang

**Pull request merged**
