### PR TITLE
remove krshapedlogic tag, this is default now

### PR DESCRIPTION
**Pull request by whaught**
- remove krshapedlogic tag, this is default now

### CODE REVIEW

**Comment by tom24d** [comment]
Is this safe? I see generated code on eventing-contrib is still not krshaped enabled, as well as not enabled on tekton side https://github.com/tektoncd/pipeline/pull/2807.

**Comment by matzew** [comment]
well, I updated the contrib, and set it as disabled - we can pick by source, no ?

**Comment by tom24d** [comment]
It is safe if we use false tag. sorry for interrupting 🤭

**Comment by whaught** [comment]
the false tag is safe, and should generate the same as before when the tag was omitted. I was trying to discover which downstreams were missed. I will follow up and investigate eventing-contrib.

**Pull request merged**
