### PR TITLE
Fix: Rename UserContainer to MainContainer

### PR DESCRIPTION
**Pull request by asr2003**
-  :broom: Rename UserContainer to MainContainer 
-
-

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by asr2003** [comment]
It's WIP

**Comment by asr2003** [comment]
Changes aren't reflected here even though comitted. Will rebase and push again the changes

**Comment by dprotaso** [comment]
This work is assigned to someone else - please look for other issues to work on. We don't want duplicate efforts.

https://github.com/knative/serving/issues/15007#issuecomment-2136240613

**Comment by asr2003** [comment]
> This work is assigned to someone else - please look for other issues to work on. We don't want duplicate efforts.
> 
> [knative/serving#15007 (comment)](https://github.com/knative/serving/issues/15007#issuecomment-2136240613)

Thanks! I have done the work. locally. I am in the queue for the issue assignment if current assignee isn't solve

**Pull request closed without merging**
