### PR TITLE
Bump to k8s v0.24.4 client packages

### PR DESCRIPTION
**Pull request by jonathan-innis**
# Changes

[Karpenter](https://github.com/aws/karpenter) uses knative injection packages in our project and are currently blocked on upgrading packages due to knative supported Kubernetes version

- This PR upgrades Kubernetes packages to `v1.24.x`

I found the development documentation lacking for how to build and test changes as well as how to use the `codegen` to generate the relevant code so please correct any of the changes that do not make sense.

/kind cleanup

Fixes #

**Release Note**

```release-note
None
```

**Docs**

```docs

```

### CODE REVIEW

**Comment by jonathan-innis** [comment]
@dprotaso I'm assuming that these tests are failing downstream due to them using `v0.23.9` of `k8s.io` packages. What is the order of operations for upgrading to the latest package. Since there is a breaking change, I'm assuming this one should go in first and the downstream changes can take dependency on `knative/pkg` and `v0.24.4` of `k8s.io` packages

**Comment by dprotaso** [comment]
/lgtm
/approve

I'll address deprecations in another PR

**Comment by dprotaso** [comment]
This PR fixes the deprecations https://github.com/knative/pkg/pull/2589

**Pull request merged**
