### PR TITLE
update gateway

### PR DESCRIPTION
**Pull request by lichuqiang**
It's dependency of https://github.com/knative/serving/pull/2434

### CODE REVIEW

**Comment by lichuqiang** [comment]
/hold
It would break compatibility. We should not merge this until knative/serving#2434 is ready.

**Comment by lichuqiang** [comment]
I update the spoof client to:
1. visit with knative-ingressgateway if it exists
2. fallback to istio-ingressgateway otherwise.

/cc @tcnghia @jonjohnsonjr Can you help clarify if this can work around the upgrade test issue?

**Comment by tcnghia** [comment]
@lichuqiang thanks for making the change.  I think this would work.

If you have a remote with your `knative/pkg` version you can update your `Gopkg.toml` to something like this to try testing against your remote
```
[[override]]
  name = "github.com/knative/pkg"
  source = "https://github.com/lichuqiang/pkg.git"
  revision = "your-commit-id"
```

**Pull request merged**
