### PR TITLE
Apply the cleanup to the pkg

### PR DESCRIPTION
**Pull request by vagababov**
This is probably the final iteration of my cleanup application.

This applies basically the same script as in the GHA.

/assign mattmoor @tcnghia

### CODE REVIEW

**Comment by vagababov** [comment]
p.s. some manual massaging was applied for even better performance.

**Review by mattmoor — COMMENTED** [review]
/lgtm

**Review by tcnghia — APPROVED** [review]

**Comment by vagababov** [comment]
Both look unreleated
/retyest

**Pull request merged**
