### PR TITLE
Fix crash looping when leader election config doesn't exist (#1142)

### PR DESCRIPTION
**Pull request by pmorie**
Cherry-pick of #1142

### CODE REVIEW

**Comment by evankanderson** [comment]
@googlebot wtf

/lgtm
/approve 

I'm guessing that this is how we want to pull this `pkg` change forward into the 0.13 release branches in other repos.

**Comment by isdal** [comment]
cla label updated. Odd.

**Comment by vagababov** [comment]
/label cla: yes
remove-label cla: no

**Pull request merged**
