### PR TITLE
bump golang version in downstream tests

### PR DESCRIPTION
**Pull request by dprotaso**
Fixes the operator downstream test which had their go version bumped to go1.19

### CODE REVIEW

**Comment by dprotaso** [comment]
cc @pierDipi looks like your api docs generating tool doesn't work with go1.20  https://github.com/ahmetb/gen-crd-api-reference-docs

We'll want to bump go to 1.20 for the next release

**Comment by houshengbo** [comment]
@dprotaso Do we target to upgrade the go version to 1.20? Or just 1.19 will be enough?

**Comment by dprotaso** [comment]
> Do we target to upgrade the go version to 1.20? Or just 1.19 will be enough?

We should use go1.20 in our toolchain. Whether or not your repo (operator) requires go1.19 or go1.20 in your go.mod is up to you.

**Pull request merged**
