### PR TITLE
Revert "Remove the unused file (#1935)"

### PR DESCRIPTION
**Pull request by markusthoemmes**
This reverts commit e45bbefd1d63e0bc82c88984cab408441378da07.

The commit was done inadvertently, we actually wanted to switch to the alias that got deleted. So let's do that now!

/assign @julz

### CODE REVIEW

**Comment by markusthoemmes** [comment]
/retest

OpenCensus stuff.

**Comment by julz** [comment]
worth adding an explicit "Deprecated:" comment on the old method to encourage people to move to the right one this time?

**Comment by markusthoemmes** [comment]
Don't think so, as that'll break the existing usages (in Knative anyway). I planned to send the fixing PR and then remove this right after the bump.

**Comment by julz** [comment]
Hm, don't totally understand how a deprecation comment would break people but removing the method won't? (I'm misunderstanding what's going on here aren't I? 😊)

**Comment by julz** [comment]
(I'm totally fine just lgtm-ing as-is if we're planning to remove the method once we've bumped serving btw, just making sure I understand the plan before stamping!)

**Review by julz — APPROVED** [review]
/lgtm

**Pull request merged**
