### PR TITLE
Add JSONTracePred

### PR DESCRIPTION
**Pull request by ian-mi**
Allows the use of an arbitrary predicate when polling a zipkin trace
ID. Enables the creation of tests in which the number of trace spans
may vary.

### CODE REVIEW

**Comment by vagababov** [comment]
Can we add the test as well, then? :)

**Comment by ian-mi** [comment]
Sorry the test is in eventing: https://github.com/knative/eventing/pull/2752, but if these helpers would be useful for serving I can move them here.

**Comment by vagababov** [comment]
This general library, so it is better to test upstream, methinks.

**Comment by ian-mi** [comment]
Do you mean a unit test for this helper? There are not currently unit tests for any of the zipkin helpers so that would increase the scope of this PR somewhat.

**Comment by vagababov** [comment]
Hm, I thought there were tests here... but ok :|
/lgtm

**Comment by ian-mi** [comment]
Thanks! I still need owner approval to merge, though.

**Comment by chizhg** [comment]
Ah sorry missed that.
/approve

**Pull request merged**
