### PR TITLE
Remove key in tags to reduce metrics count

### PR DESCRIPTION
**Pull request by lanceliuu**
Issue: https://github.com/knative/serving/issues/8609

Signed-off-by: Lance Liu <xuliuxl@cn.ibm.com>

### CODE REVIEW

**Comment by evankanderson** [comment]
You probably also want to remove `keyTagKey` from line 170 and 175 (which is where we instruct OpenCensus to aggregate divided by `key`), and the definition on line 49.

**Comment by lanceliuu** [comment]
I removed the key tag accordingly. Thank you @evankanderson.
After apply this patch, the total metrics count for controller drops significantly.
Before:
```
~ wc -l metrics-controller.txt
   68628 metrics-controller.txt
```
After:
```
~ wc -l metrics-controller.txt
     570 metrics-controller.txt
```
Also the size of metrics drops from ~11M to ~66K
@vagababov

**Comment by evankanderson** [comment]
Wow, the cardinality for `key` must have been really high (which will cause problems with Stackdriver, at least, but many monitoring systems struggle with high-cardinality labels).

/lgtm
/approve

**Pull request merged**
