### PR TITLE
use coordination.Leases exclusively for leader election

### PR DESCRIPTION
**Pull request by dprotaso**
Prior locks were for K8s version <1.14

Fixes: #1427

I left the plumbing of the lock setting through everything since there may be a new lock in the future we would want to switch to - if folks feel like this is unnecessary let me know and I can rip it out

### CODE REVIEW

**Comment by markusthoemmes** [comment]
Is this a "breaking" change? Do we need to check if anybody is using something different than leases first?

**Comment by dprotaso** [comment]
> Is this a "breaking" change? Do we need to check if anybody is using something different than leases first?

Technically this feature is alpha so breaking changes are allowed

**Comment by mattmoor** [comment]
According to @pmorie (in slack) the Operator doesn't reference this field, and the docs I just updated don't mention configuring this.  I believe we've also established that all supported K8s versions have had the coordination API (probably since the inception of this feature).

I agree that this is breaking, but also that it's alpha and now's the time to make breaking changes.  @markusthoemmes beyond this simply being available in prior releases, do you have reason to think this might present problems?

**Comment by markusthoemmes** [comment]
Nope, just pointing out it's potentially breaking and making sure we though about it. That seems to be the case :yum: . I got no objections beyond that.

**Comment by dprotaso** [comment]
cool - can someone approve/lgtm this change and I'll go to the various repos and drop the lock types from the configs

**Pull request merged**
