### PR TITLE
Update OWNERS_ALIASES to match autogen in community

### PR DESCRIPTION
**Pull request by evankanderson**
See https://github.com/knative/community/pull/552 for the addition of groups/full OWNERS_ALIASES that will be synced.

This is a preparatory PR for landing OWNERS_ALIASES automation across the Knative org (alternative to the CODEOWNERS changes in knative-sandbox).

If this seems to be expanding permissions or otherwise likely to cause a problem, `/hold` this PR and comment here or on https://github.com/knative/community/pull/552.

### CODE REVIEW

**Comment by evankanderson** [comment]
/assign @vagababov @markusthoemmes @dprotaso 

Picking a few people who may have opinions here.

/hold

In case one of those three wants to raise objections.

**Comment by dprotaso** [comment]
Sorry - I gave precedence to this https://github.com/knative/pkg/pull/2061 cause it was first

**Review by evankanderson — COMMENTED** [review]
Updated, added `skonto` directly since there was only one use of `metrics-reviewers` in the OWNERS files. If we need more directories with the same OWNERS, we can add them via peribolos to the autogen in the future.

**Comment by dprotaso** [comment]
/lgtm
/approve

Going to let someone else unhold so we get a second set of eyes

**Review by markusthoemmes — APPROVED** [review]
LGTM

I'd say let's pull this in and fix any aftermath if we have any. The contents of this are reasonable from my PoV, but it's a bit hard to review.

**Pull request merged**
