### PR TITLE
Add logic to check the licenses of our common package

### PR DESCRIPTION
**Pull request by mattmoor**
This is WIP (and broken!) until we update `dep-collector` to support files named `LICENCE`...

### CODE REVIEW

**Comment by mattmoor** [comment]
Needs: https://github.com/knative/test-infra/pull/209 https://github.com/knative/test-infra/pull/210 and a fresh vendor of `test-infra`...

**Comment by mattmoor** [comment]
I also pushed an update to `mattmoor/dep-collector` with the fix I sent to the `test-infra` copy, but the `go get -u` doesn't seem to trigger in the Prow image, so I think that image will need an update regardless of the test-infra changes I've made.  cc @adrcunha

**Comment by mattmoor** [comment]
Locally I now see:
```
-----------------------------------------
---- Checking for forbidden licenses ----
-----------------------------------------
2018/10/25 19:31:08 No errors found.
```

**Comment by mattmoor** [comment]
I take that back, if I `rm $GOPATH/bin/dep-collector` I see:
```
-----------------------------------------
---- Checking for forbidden licenses ----
-----------------------------------------
2018/10/25 19:32:27 Error identifying licenses for transitive dependencies: unable to find license for "github.com/knative/pkg/vendor/github.com/joho/godotenv"
```

**Comment by srinivashegde86** [comment]
Uploaded a new image.

/retest

**Pull request merged**
