### PR TITLE
move some spoof helpers to the spoof package

### PR DESCRIPTION
**Pull request by dprotaso**
This helps avoid pulling in the pkg/test globals

Note: I left aliases so this shouldn't be a breaking change

### CODE REVIEW

**Comment by dprotaso** [comment]
new flake configmap - TestInformedWatcher

https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_pkg/1827/pull-knative-pkg-unit-tests/1318663218943496192

/retest

**Review by vagababov — COMMENTED** [review]
/lgtm

**Comment by dprotaso** [comment]
had to rebase - github actions don't merge HEAD so downstream bumping breaks

**Comment by vagababov** [comment]
yeah I looked and saw all the failures from like october so I ignored them

**Pull request merged**
