### PR TITLE
bump to latest k8s patch (0.23.9)

### PR DESCRIPTION
**Pull request by dprotaso**
/assign @nader-ziada @psschwei

### CODE REVIEW

**Review by psschwei — COMMENTED** [review]
/lgtm

**Comment by psschwei** [comment]
Downstream Tekton failure seems to be because Tekton isn't using the new changeset.Get() just yet ([discussion in pipelines repo](https://github.com/tektoncd/pipeline/pull/4928#discussion_r927697033)). Assuming this is our first chance to test out using  `/override` on a GH Action @dprotaso ?

**Comment by dprotaso** [comment]
/override Downstream Tekton / Unit Test (tektoncd/pipeline)

**Comment by dprotaso** [comment]
GitHub actions are optional now
- https://github.com/knative/test-infra/pull/3463

**Pull request merged**
