### PR TITLE
Add Istio DestinationRule and Policy into Istio apis and clients

### PR DESCRIPTION
**Pull request by ZhiminXiang**
1. Add Istio [DestinationRule](https://github.com/istio/api/blob/master/networking/v1alpha3/destination_rule.proto) and [Policy](https://github.com/istio/api/blob/master/authentication/v1alpha1/policy.proto) into Istio apis.
We need DestinationRule and Policy for enabling mutual TLS within Knative.

2. Update hack/update-codegen.sh so that it can automatically generate Policy related code.
3. Move StringMatch from istio/v1alpha1/virtualservice_types.go to istio/common/v1alpha1/string.go to follow the [pattern](https://github.com/istio/api/tree/master/common/v1alpha1) of Istio
3. Run hack/update-codegen.sh to automatically generate clients for DestinationRule and Policy

### CODE REVIEW

**Comment by ZhiminXiang** [comment]
@mattmoor would you mind taking a look at this PR? :) Thanks!

**Comment by mattmoor** [comment]
/approve

You need to resolve the conflicts

**Comment by ZhiminXiang** [comment]
Merge conflicts were resolved. Could @mattmoor and @tcnghia give me an approval? Thanks!

**Pull request merged**
