### PR TITLE
bump k8s to v1.20.7

### PR DESCRIPTION
**Pull request by dprotaso**
Fixes: https://github.com/knative/pkg/issues/2111

### CODE REVIEW

**Comment by dprotaso** [comment]
hmm... that won't work cause they make a copy of gvrToList map

**Comment by dprotaso** [comment]
This PR should make eventing green: https://github.com/knative/eventing/pull/5477 downstream.

Other changes are trivial string replacements with the exception of the client & a plugin

**Comment by markusthoemmes** [comment]
Doublechecked the downstream failures:

* Serving has the same "different error message" thing that this has, trivial to fix
* Networking has the same.
* Client has a compile error. Would it make sense to stage that change first?
* Camel has already been dropped, so we can ignore.
* kn-plugin-admin has the same compile error as client, so I guess fixing client will fix it as well.

So this is LGTM! Thanks for unblocking that breaking change!

**Comment by markusthoemmes** [comment]
FWIW, just looked at the client failure: `k8s.io/cli-runtime` has to be bumped to 0.20.7 in that repo too (it's not inherited from here) and then a few tests fail due to that dynamic client breaking change. Alerted the client team about that and now waiting for confirmation to either go ahead or to stage a fix first.

**Review by markusthoemmes — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
