### PR TITLE
Adding a gke tag to let pkg tests run on a system without google creds installed

### PR DESCRIPTION
**Pull request by n3wscott**
Related to https://github.com/knative/pkg/issues/958

### CODE REVIEW

**Comment by n3wscott** [comment]
fixes https://github.com/knative/pkg/issues/934

**Comment by adrcunha** [comment]
This is the wrong fix. I agree that the unit tests should not be relying on real interactions with GKE. But tagging them is just silently excluding them from presubmit tests (which are currently running fine) and zeroing test coverage in that package (thus risking introducing bugs without authors noticing).

/hold

**Comment by n3wscott** [comment]
> (which are currently running fine)

It is only running fine because it has gcloud and is authed to google.

I am not able to run `go test ./...` in knative/pkg locally. So I can't run the unit tests because the unit tests have external deps.

**Comment by adrcunha** [comment]
> > (which are currently running fine)
> 
> It is only running fine because it has gcloud and is authed to google.

Yes, because gcloud is setup on the Prow jobs.

> I am not able to run `go test ./...` in knative/pkg locally. So I can't run the unit tests because the unit
> tests have external deps.

Right. That's why the right fix is to remove such dependency instead of knocking out the tests.

**Comment by n3wscott** [comment]
@adrcunha anyone working on a fix? All this gke stuff breaks testing on anything else.

**Comment by adrcunha** [comment]
Not that I am aware of.

**Comment by chizhg** [comment]
> @adrcunha anyone working on a fix? All this gke stuff breaks testing on anything else.

I'll take care of it.

**Comment by chizhg** [comment]
Fixed in https://github.com/knative/pkg/pull/963

/close

**Pull request closed without merging**
