### PR TITLE
Drop spec.generation support

### PR DESCRIPTION
**Pull request by dprotaso**
With Kubernetes 1.11+ metadata.generation now increments properly
when the status subresource is enabled on CRDs

Thus we can drop
- the webhook logic incrementing `spec.generation`
- the generational duck type

Addresses part of knative/serving#643

Holding for now - since I will prepare PRs in other repos incorporating this change
/hold

### CODE REVIEW

**Comment by mattmoor** [comment]
/assign @vaikas-google 

I'll be glad to see this gone.  I'll let @vaikas-google do the honors :)

**Comment by vaikas-google** [comment]
awesome!!
/lgtm
/approve

**Comment by mattmoor** [comment]
/lgtm

@dprotaso Remove the hold when you are ready to pull the trigger on the other repos?

**Comment by dprotaso** [comment]
- [ ] serving - https://github.com/knative/serving/pull/3219
- [ ] build - TODO
- [ ] build-pipeline - https://github.com/knative/build-pipeline/pull/367

**Comment by dprotaso** [comment]
everything went green 

/hold cancel

**Pull request merged**
