### PR TITLE
Bump min kubernetes to v1.23

### LINKED ISSUE #2594: Make K8s 1.23 mandatory
We'll want to bump the min version in pkg 

see: https://github.com/knative/pkg/pull/2485

/assign @psschwei

### PR DESCRIPTION
**Pull request by psschwei**
Signed-off-by: Paul S. Schweigert <paul@paulschweigert.com>

# Changes

Fixes #2594

### CODE REVIEW

**Comment by skonto** [comment]
```
vendor/k8s.io/cli-runtime/pkg/resource/dry_run_verifier.go:78:34: cannot use oapi (variable of type *"github.com/google/gnostic/openapiv2".Document) as type *"github.com/googleapis/gnostic/openapiv2".Document in argument to supportsDryRun
```

**Comment by matzew** [comment]
@psschwei @skonto what does prevent us from merging this?

**Comment by psschwei** [comment]
> @psschwei @skonto what does prevent us from merging this?

Nothing I'm aware of, just needs a review

**Pull request merged**
