### PR TITLE
Remove ClearAll from the codebase

### PR DESCRIPTION
**Pull request by vagababov**
now that I've verified it does not exist in any of the repos that are of any importance
we can remove it :-)

/assign mattmoor @taragu

### CODE REVIEW

**Comment by n3wscott** [comment]
```--- FAIL: TestInformedWatcher (0.00s)```

**Comment by vagababov** [comment]
/retest

(ノಠ益ಠ)ノ彡┻━┻

**Comment by vagababov** [comment]
cc @evankanderson  — we need to fix those :/
/retest

**Pull request merged**
