### PR TITLE
Delete deprecated ObserveFinalizeKind API

### PR DESCRIPTION
**Pull request by markusthoemmes**
# Changes

Shaking the :evergreen_tree:, here's hoping nobody actually implements it and if they do, imma make them not do it :joy:

### CODE REVIEW

**Comment by lionelvillard** [comment]
/hold

are you sure? This is breaking a lot of downstream repos

**Comment by dprotaso** [comment]
blah sorry - yeah I missed that.

@markusthoemmes we should leave the older interfaces around until the changes that update the generated code proliferate a bit

**Comment by markusthoemmes** [comment]
This actually looks like the downstream test action is wrong :thinking:. After an update-codegen, everything should be fine.

**Comment by markusthoemmes** [comment]
Ahhhh very good point @dprotaso, thanks! That actually explains all the breaks, I think.

**Comment by markusthoemmes** [comment]
@dprotaso @lionelvillard kept the opposing constant in for now. Once pkg updates have rolled through, we can delete that as well.

**Comment by antoineco** [comment]
Uh-oh, I [do use that](https://github.com/triggermesh/aws-event-sources/blob/13d3cd242c94c32ff7539c541fa83ed5cd0e9416/pkg/adapter/awssnssource/reconciler.go#L85) 😊 

I believe a sound alternative is to use an event handler on Delete, is that what you folks do?

**Comment by markusthoemmes** [comment]
@antoineco you'll want to switch over to the solution implemented via https://github.com/knative/pkg/issues/2021

**Pull request merged**
