### PR TITLE
Various stuff around the logstream

### PR DESCRIPTION
**Pull request by vagababov**
- handle `event.Object == nil` case. We have reports of this. Strange
  edgecase, but :shrug:.
- add tons of tests around various cases, should raise the coverage a
bit (although, we exclude test, still should be better).

/assign @dprotaso @tcnghia @markusthoemmes

### CODE REVIEW

**Review by vagababov — COMMENTED** [review]
/cc @arturenault

**Review by tcnghia — APPROVED** [review]
/lgtm

**Comment by tcnghia** [comment]
/hold
@vagababov seems some related tests are failing

**Comment by vagababov** [comment]
fixed lint
/unhold

**Review by tcnghia — APPROVED** [review]
/lgtm

**Comment by tcnghia** [comment]
/unhold

(seems to be only failing unrelated tests now)

**Pull request merged**
