### PR TITLE
allow overriding spoofed gateway name/namespace

### PR DESCRIPTION
**Pull request by ilackarms**
This PR is designed to enable running knative serving tests against an ingress other than Istio. For those lacking context, [Gloo, the Envoy-based Kubernetes Ingress / API Gateway](https://gloo.solo.io/) can now [serve as a clusteringress controller for knative-serving](https://gloo.solo.io/getting_started/kubernetes/gloo_with_knative/).

### CODE REVIEW

**Comment by ilackarms** [comment]
`I signed it!`

**Comment by tcnghia** [comment]
/lgtm

@jessiezcc can you please help approve?  thanks

**Pull request merged**
